### ISSUE TITLE
Feature Request: modbus/tcp support

### ISSUE THREAD

**Issue by aw1604** [dxoverdy/Alpha2MQTT#16]
Hello,
Would it be possible to add direct modbus/tcp support ? For example, the Smile-T10 with current software update supports modbus on port 502/tcp (and I can pull data using home-assistant modbus/tcp directly). So basically I'm just missing the AlphaESS-Frontend, while the data is already in HA without any ESP/serial-to-network controller.

Best Regards,
Andreas

PS: I am not a coder, but willing to sponsor some work on this

**Comment by dxoverdy** [comment]
I converted 80% into Python as I would rather use modbus over tcp but at
the last minute Alpha told me the Smile B3 doesn’t support it so I can’t
develop it further, unless someone with a working tcp ip device could give
me access to their home assistant and network details of their alpha system
so I can finish it.

There is also less interest to fight too seeing as I can’t benefit from
what I do ha!

**Comment by dc42** [comment]
@aw1604 I didn't realise that Alpha ESS had implemented Modbus TCP yet, the last I heard was that it was planned. What settings in configuration.yaml are you using to access your inverter? I just tried the following but it isn't working:

```
modbus:
  - name: SMILE5
    type: tcp
    host: 192.168.1.70
    port: 502
    sensors:
      - name: "Grid power"
        slave: 0x55
        address: 0x0021
        input_type: holding
        unit_of_measurement: W
        state_class: measurement
        count: 2
        data_type: int32
        scan_interval: 10
        unique_id: "modbustcp_grid_power"
```
