### ISSUE TITLE
Set charge / discharge times?

### ISSUE THREAD

**Issue by Spookster** [dxoverdy/Alpha2MQTT#8]
*Havent installed yet
Before I dive in, is there a documented way to set discharge / charge times from the interface via code example? (Home Assistant)
Im running a SMILE5 and the documentation and HA Dashboards youve provided doesnt seem to cover that specifically (although it would be possible)

Does anyone have a HA example? or did I miss it?

![image](https://github.com/dxoverdy/Alpha2MQTT/assets/982535/529f0079-9ef5-408b-97f0-a2b689873bd9)

**Comment by dxoverdy** [comment]
The registers here (
https://github.com/dxoverdy/Alpha2MQTT/blob/4966f1f971f7648a23bdbb75225ca94c7a37ab1e/Alpha2MQTT/Definitions.h#L398)
write those settings.

For example, writing 1 to  REG_TIMING_RW_TIME_CHARGE_START_TIME_1
Will set a start charge time of 00:01.

Alternatively, you can set charge or discharge via an mqtt message.

Dan

**Comment by Spookster** [comment]
So theres nothing in the Alpha Write Register HA pages that specifically set it? (ie no dashboard pages that people have created specifically for that control?)
Ill delve in deeper once its running
Thanks Dan, your work seems like just what I want.. let the fun begin.....

**Comment by Spookster** [comment]
So this would give a time of 0.01?

```
service: mqtt.publish
data:
  retain: false
  topic: Alpha2MQTT/request/write/register/raw/data
  payload:
    registerAddress: "0x0851"
    value: 1
    dataBytes: 2
  qos: "0"
```
And this 2300?
```
service: mqtt.publish
data:
  retain: false
  topic: Alpha2MQTT/request/write/register/raw/data
  payload:
    registerAddress: "0x0851"
    value: 2300
    dataBytes: 2
  qos: "0"
```
